const britishGarden = {
  name: 'British Garden',
  ids: [
    'blue-tit',
    'great-tit',
    'house-sparrow',
    'robin',
    'blackbird',
    'wren',
    'starling',
    'wood-pigeon',
    'goldfinch',
    'magpie',
    'long-tailed-tit',
    'song-thrush',
    'greenfinch',
    'coal-tit',
    'siskin',
    'chaffinch',
    'chiffchaff',
    'sparrowhawk',
    'song-thrush',
    'starling',
  ],
}

const stAidans = {
  name: 'Wetlands',
  ids: [
    'cettis-warbler',
    'bittern',
    'black-headed-gull',
    'great-crested-grebe',
    'little-grebe',
    'black-necked-grebe',
    'long-tailed-tit',
    'shoveler',
    'little-owl',
    'short-eared-owl',
    'kestrel',
    'goldeneye',
    'redshank',
    'brambling',
    'great-white-egret',
    'tufted-duck',
    'mallard-duck',
    'wigeon',
    'lapwing',
    'curlew',
    'teal',
    'cormorant',
    'coot',
    'moorhen',
  ],
}

export const groups = {
  britishGarden,
  stAidans,
}
